
Geo Data Science with Python,
Prof. Susanna Werth, VT Geosciences

# Data (and) Arrays


This notebook accompanies the lecture L02 presentation slides.

---


Content:
-------
- Linear Algebra
- Numpy arrays
- Vectorization
- Broadcasting, Filtering, Masks


---
## Part 1: Matrix Algebra & NumPy Arrays


In [1]:
import numpy as np

${\large \text{What happens when you import something?}}$

${\large \text{You load a python file,i.e. a .py file, with}}$

${\large \hspace{24pt} \text{+ Object class definitions}}$

${\large \hspace{24pt} \text{+ Function and method definitions}}$

${\large \hspace{24pt} \text{+ Variable assignments (have to be careful)}}$

In [2]:
# Create different tensor types as numpy arrays
np.random.seed(0) # seed for reproducibility

s = 3                                      # scalar (0D)
v = np.random.randint(10, size=6)         # vector (1D) array
m = np.random.randint(10, size=(4, 4))    # matrix (2D) array
t = np.random.randint(10, size=(3, 4, 5)) # 3D tensor array


# Alternatively, manual creation for syntax check
s = 3                            # scalar (0D)
vm = np.array([1,2,3])           # vector (1D)
vmc = np.array([[1],[2],[3]])    # column vector 
vmr = np.array([[1],[2],[3]])    # row vector 
mm = np.array([[1,2,3],[4,5,6]]) # matrix (2D)
tm = np.array([ [ [1,2,3],[4,5,6] ] ,
             [ [7,8,9],[9,8,7] ]  ])  # 3D tensor


In [3]:
## Formatted print of 2d array

for r in range(3):
    for c in range(4):
        print('%4d' %m[r][c], end = ' ')
    print('')

   3    5    2    4 
   7    6    8    8 
   1    6    7    7 


In [4]:
## Print some numpy methods for understanding data

varPr = m # x1, x2, x3   # CHOOSE VARIABLE HERE

print('Array dtype:    ', varPr.dtype) # Data type
print("Array ndim:     ", varPr.ndim)  # dimension of the array
print("Array shape:    ", varPr.shape) # shape of the array
print("Array size:     ", varPr.size)  # number of elements
print("Array Val size: ", varPr.itemsize) # bytes of each element


Array dtype:     int64
Array ndim:      2
Array shape:     (4, 4)
Array size:      16
Array Val size:  8


In [5]:
# Vector and Matrix Properties

mT    = m.T              # transpose
mDiag = m.diagonal()     # get diagonal
mInv  = np.linalg.inv(m) # inverse
mDet  = np.linalg.det(m) # determinant


In [17]:
# Special Matrices and Arrays

mi = np.identity(4)      # Identity matrix, 4x4, also: np.eye()
m_one = np.ones([4,4])   # 4x4 matrix filled with ones
m_zero = np.zeros([4,4]) # 4x4 matrix filled with zeros

# also useful:

# np.full((2,2,2),3)      # ... filled with given number
# np.full((3, 3), np.nan) # 3x3 array filled with NaN
# np.full(2, np.inf)      # 2x1 array filled with Inf
# np.arange(3,7)     # evenly spaced values (with integer spacing)
# np.linspace(1,5,9) # n evenly spaced numbers over a specified interval


In [7]:
# Basic Operations

res1 = 10*m     # Skalar multiplication
res2 = m + m    # Addition
res3 = m - m    # Substraction
res4 = m * m    # Element-by-element Multiplication (Hadamard Product)
res5 = m @ m.T  # Dot Product (Inner Product)


In [8]:
# Hadamard vs. Dot Product

hadProd  = m * mi   # results in diagonal only
dotProd  = m @ mi   # equal to m (neutrality of the identity matrix!)
dotProdI = mi @ mi  # equal to identity matrix


In [9]:
# Neutrality of the identity matrix: M@I=M

m @ mi == m   # all true!


array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [10]:
# Matrix inverse & identity check: M@M^-1=I

np.set_printoptions(precision=2, suppress=True) # change output format to read better
m @ mInv 


array([[ 1., -0.,  0., -0.],
       [ 0.,  1.,  0.,  0.],
       [ 0., -0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

### Exercise: Solve the following linear equation system

Assume we build a simple hydraulic model between groundwater heads h and pumping rates x1, x2 and x3:

\begin{cases}
h_1 = 2x_1 + x_2 - x_3 = 3 \\
h_2 = - x_1 + 3x_2 + 2x_3 = 12  \\
h_3 = 3x_1 - 2x_2 + 4x_3 = 5
\end{cases}

If Ax = h, what are the matrices A and h? Then solve for x using linear algebra!

In [11]:

# Coefficient matrix

# Right-hand side

# Solve for x, y, z

#print("Solution:", solution)


---
## Part 2: Vectorization


### Tutorial 1

Below, a big array of length 1000 is filled with random numbers.

In [27]:
bigArray = np.random.randint(1, 100, size=10000) 
bigArray.shape

(10000,)

Apply any arithmetic operator to this vector in two ways, e.g. reciprocal of vector elements:
1. Write a function that uses a for loop, iterating through the vector and calculating the operation and saving the output to a new array variable
2. In a separate code cell: use equivalent NumPy operator for the same operation (as of previous table)

Use the magic command `%timeit` to measure the execution time and compare them for both ways.

In [ ]:
# add your code


---
## Part 3: Broadcasting, Indexing, Filtering, Masking of Arrays

#### Copies vs. views

In [51]:
# First, copies versus views:

m_view = m[2,:]       # does not create a new object
m_copy = m[2,:].copy() # creates a new (sliced) object

# Alter one of the elements and see what happens to m?!


In [60]:
m_view[0] = 0
m # does change - be careful!

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [0, 6, 7, 7],
       [8, 1, 5, 9]])

In [61]:
m_copy[0] = -1
m # does not change

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [0, 6, 7, 7],
       [8, 1, 5, 9]])

#### What is Fancy Indexing ?

In [86]:
v

array([5, 0, 3, 3, 7, 9])

In [89]:
fancyIndices = [0,3,5]  # create an array of indices

In [90]:
v[fancyIndices]         # pass the array of indices for indexing

array([5, 3, 9])

#### Rules of broadcasting

In [34]:
# Rules of broadcasting:

twoDimArray = np.array([  [1, 2, 3],
                          [4, 5, 6]  ])
oneDimArray = np.array([100]) 
output = twoDimArray + oneDimArray
print("Broadcasting result:\n", output)

# Helps to keep code vectorized and prevents repetition of data


Broadcasting result:
 [[101 102 103]
 [104 105 106]]


In [36]:
# broadcasting does vectorize the following thing for you

numRow, numCol = twoDimArray.shape
output = twoDimArray.copy()
for row in range(numRow):
    for col in range(numCol):
        output[row][col] += oneDimArray[0] # this oneDimArray only has 1 element
print("For loop result:\n", output)

For loop result:
 [[101 102 103]
 [104 105 106]]


#### Filtering

In [115]:
m[m>5] # use a boolean test test result to filter out values


array([7, 6, 8, 8, 6, 7, 7, 8, 9])

In [116]:
m[~(m>5)] # invert the filter

array([3, 5, 2, 4, 0, 1, 5])

#### Filtering using a mask

When we filter data like this, a mask is created. The mask consists of True/False or 1/0 arrays:

In [96]:
mask = v>5
mask

array([False, False, False, False,  True,  True])

In [97]:
v[mask]

array([7, 9])

- Masking/Filtering works for arrays of any dimensions
- It is also vectorized
- It can be applied with or without broadcasting:

In [101]:
m

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [0, 6, 7, 7],
       [8, 1, 5, 9]])

In [108]:
mask = [True,True,False,False]
mask

[True, True, False, False]

In [112]:
m[mask]   # broadcasted along rows (repeated for every row)

array([[3, 5, 2, 4],
       [7, 6, 8, 8]])

In [113]:
m[:,mask] # applied along columns

array([[3, 5],
       [7, 6],
       [0, 6],
       [8, 1]])

In [ ]:
m[mask,:] # applied along rows

#### 3D array and 2D mask
Now let's do the same for a 3D and a 2D vector.
This can be helpful for spatiotemporal maps!

In [128]:
# let's reuse the 3x4x5 tensor from earlier

mask2D = t[0,:,:]>4
mask2D


array([[ True, False, False,  True, False],
       [False, False, False,  True,  True],
       [ True,  True,  True, False, False],
       [False, False, False,  True,  True]])

Keep in mind that matrices in tensor are axis 1 and 2 (not 0), e.g. for a spatiotemporal map, maps could be on axis 1 and 2 and the time would be on axis 1.

Then the mask can be applied at every time step:

In [132]:
t[:,mask2D]
# The resulting three rows are filtered values from the map at each time step. 

array([[7, 8, 9, 6, 7, 5, 9, 8, 6],
       [9, 8, 1, 2, 8, 7, 9, 9, 5],
       [5, 7, 3, 5, 8, 5, 5, 1, 0]])

#### Try this on real data! Proceed with Task 3 of this week's homework.